# Tensors

In [3]:
import torch
import numpy as np

In [4]:
data = [[10,20],[30,40]]
x = torch.tensor(data)
print(x, '\n',type(x))

tensor([[10, 20],
        [30, 40]]) 
 <class 'torch.Tensor'>


In [5]:
np_array = np.array(data)
torch_array = torch.from_numpy(np_array)
print(torch_array,'\n', type(torch_array))

tensor([[10, 20],
        [30, 40]]) 
 <class 'torch.Tensor'>


In [6]:
ones = torch.ones_like(x)
rand = torch.rand_like(x, dtype=torch.float)
print(ones, '\n',rand,'\n',type(ones), type(rand), rand.dtype, rand.device)

tensor([[1, 1],
        [1, 1]]) 
 tensor([[0.3297, 0.5488],
        [0.7475, 0.3297]]) 
 <class 'torch.Tensor'> <class 'torch.Tensor'> torch.float32 cpu


In [7]:
shape = (2,3)
print(torch.rand(shape),'\n', torch.ones(shape),'\n', torch.zeros(shape))
print(torch.rand_like(shape),'\n', torch.ones_like(shape),'\n', torch.zeros_like(shape))

tensor([[0.1517, 0.5873, 0.5516],
        [0.5175, 0.1752, 0.4160]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


TypeError: ignored

## Operations on Tensors

In [10]:
# tensor = torch.device.type
if torch.cuda.is_available():
  tensor = x.to('cuda')
print(torch.cuda.is_available(), tensor.device)

True cuda:0


In [11]:
tensor = torch.ones(4, 4)
print('First row: ',tensor[0])
print('First column: ', tensor[:, 0])
print('Last column:', tensor[..., -1])
tensor[:,1] = 0
print(tensor)

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [14]:
# Joining tensor
t1 = torch.cat([x, rand, ones])
print(t1)

tensor([[10.0000, 20.0000],
        [30.0000, 40.0000],
        [ 0.3297,  0.5488],
        [ 0.7475,  0.3297],
        [ 1.0000,  1.0000],
        [ 1.0000,  1.0000]])


In [18]:
# Arithmetic Comparison
x= torch.tensor(data, dtype=torch.float)
y1 = x @ x.T
y2 = x.matmul(x.T)

y3 = torch.rand_like(x, dtype=torch.float)
print(torch.matmul(x, x.T, out=y3))

z1 = x * x
z2 = x.matmul(x)

z3 = torch.rand_like(x)
print(torch.mul(x, x, out=z3))

tensor([[ 500., 1100.],
        [1100., 2500.]])
tensor([[ 100.,  400.],
        [ 900., 1600.]])


In [19]:
# Single element tensors
agg = z3.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

3000.0 <class 'float'>


In [20]:
# in-place operation
z3.sub(100)

tensor([[   0.,  300.],
        [ 800., 1500.]])

In [23]:
# Bridge with numpy
t = ones.numpy()
print(t, type(t))

[[1 1]
 [1 1]] <class 'numpy.ndarray'>


In [27]:
ones.add_(1)
print(t, ones)

[[12 12]
 [12 12]] tensor([[12, 12],
        [12, 12]])
